name: Docker CI/CD script

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./dockerfile
          tags: jja08111/camstudy-media-router:latest
          build-args: |
            PORT=${{ secrets.PORT }}
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SSH_IP_ADDRESS }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          debug: true
          port: 22
          script: |
            cd ~/camstudy-webrtc-router
            sudo docker login
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/camstudy-media-router:latest
            sudo docker stop camstudy_media_router
            sudo docker rm camstudy_media_router
            sudo docker run -d --name camstudy_media_router \
              -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/camstudy-media-router:latest
            sudo docker image prune -a -f
            echo "success";
